#!/bin/bash
#powered by amal
#this code is always opensource. feel free to edit or customize it.

echo "Checking if eligible for root permissions."

#sudo ./install
sudo echo "zsh autoinstaller is now installing...
"
echo "Checking network connection...
"
ping -c 4 www.google.com
echo "Setup is now installing requirements...
"
#pacman -S zsh zsh-completions lsb-release
./os/installer
echo "Preparing Installer...
"
cp zshrc .zshrc
sleep 5
echo "Please Wait...
"
echo "Copying Plugins.
"
sleep 2
chmod -R 755 plugins
cp -r plugins/ /usr/share/zsh
echo "Copying zsh configuration to User's folder.
"
sleep 2
chmod -R 777 .zshrc
cp -r .zshrc ~/
echo "Copying zsh configuration to /root.
"
sleep 2
cp -r .zshrc /root
sleep 3
echo "Changing permissions...
"

chmod -R 777 /home/*/.zshrc
chmod -R 777 /root/.zshrc
sleep 2
echo "Finishing touches. please wait..."
sleep 5
touch /usr/share/zsh/plugins/zsh-syntax-highlighting/.version
touch /usr/share/zsh/plugins/zsh-syntax-highlighting/.revision-hash
echo "Installation Finished. Please run chsh -s /bin/zsh for each user to change shell manually."
echo "exiting..."

exit
exit
