#!/bin/bash
echo "Installing for dpkg..."
##debian
sudo apt-get install zsh zsh-completions lsb-release

echo "Installing for archlinux..."
##arch-linux
sudo pacman -S zsh zsh-completions lsb-release

echo "Installing for fedora..."
##fedora
sudo dnf install zsh zsh-completions lsb-release

echo "Script run successfully. Exiting."
